In [1]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.43313085 0.27401274 0.6360334 ]
  [0.93077201 0.5632645  0.82396855]
  [0.30682601 0.01017504 0.16084088]]

 [[0.57272043 0.72500162 0.67377091]
  [0.20095514 0.23475262 0.40074917]
  [0.76418971 0.18666667 0.13590341]]

 [[0.46634897 0.64636867 0.49448213]
  [0.91822685 0.4784045  0.41431984]
  [0.13292975 0.08137344 0.38496064]]]


In [2]:
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [3]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [4]:
import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.58163455 0.06179629 0.84493788 0.16262332 0.51547774]
 [0.59547572 0.0169443  0.85035816 0.33114022 0.93892071]
 [0.52366968 0.71009517 0.15614697 0.84553104 0.51967663]
 [0.8475182  0.55320241 0.31685695 0.73170408 0.89521779]
 [0.01861302 0.73502602 0.02883481 0.48437392 0.94585495]]
After normalization:
[[0.60790588 0.04828451 0.89135977 0.15682781 0.5366861 ]
 [0.62280631 0.         0.89719486 0.33824127 0.99253509]
 [0.54550497 0.74619757 0.14985582 0.89199832 0.54120634]
 [0.89413756 0.57729784 0.32286491 0.7694602  0.94548758]
 [0.00179642 0.77303638 0.01280048 0.50320192 1.        ]]


In [5]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


In [6]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


In [7]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[0 0 0 0 1 0]
Second array:
[0 1 0 0 1 0]
Test above two arrays are equal or not!
False


In [10]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by -1:")
print(x)



Original array:
[0.44824254 0.11813132 0.27499666 0.94378739 0.87427972 0.90690729
 0.56819459 0.88184218 0.44422378 0.67510256]
Maximum value replaced by -1:
[0.44824254 0.11813132 0.27499666 0.         0.87427972 0.90690729
 0.56819459 0.88184218 0.44422378 0.67510256]


o print out the entire two dimensional array we can use python for loop as shown below. We use end of line to print out the values in different rows. from array import * T = [ [11, 12, 5, 2], [15, 6,10], [10, 8, 12, 5], [12,15,8,6]] for r in T: for c in r: print(c,end = " ") print()

In [11]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.52186047 0.1816809  0.08960264 0.88028354 0.6032078  0.35643983
  0.30929329 0.16107889 0.45454256 0.44818123]
 [0.04689956 0.99641494 0.10494296 0.64135676 0.29487874 0.18245699
  0.48784789 0.35327349 0.93140039 0.57259121]
 [0.77504762 0.99979365 0.65111732 0.61143664 0.89679508 0.3998409
  0.62137624 0.28768129 0.82074079 0.73975749]
 [0.87575934 0.42632106 0.64035818 0.58815845 0.26162507 0.35571017
  0.2996275  0.98863218 0.81153427 0.08689939]
 [0.21860997 0.32579987 0.85212156 0.75312954 0.86774971 0.11926828
  0.42909584 0.82117477 0.89345425 0.0499411 ]]

Subtract the mean of each row of the said matrix:

[[ 0.12124336 -0.21893621 -0.31101448  0.47966642  0.20259068 -0.04417728
  -0.09132383 -0.23953823  0.05392544  0.04756411]
 [-0.41430673  0.53520865 -0.35626333  0.18015047 -0.16632756 -0.27874931
   0.0266416  -0.10793281  0.4701941   0.11138492]
 [ 0.09468891  0.31943495 -0.02924138 -0.06892206  0.21643637 -0.2805178
  -0.05898246 -0.39267741  0.140

In [15]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)


[2. 3. 3. 4. 2. 2. 4. 4. 3. 3.]


In [ ]:
# Slow version
np.diag(np.dot(A, B))
# Fast version
np.sum(A * B.T, axis=1)
# Faster version
np.einsum("ij,ji->i", A, B).

In [12]:
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())


Original array:
[4 0 9 6 8 0 4 8 4 4 7 4 8 9 5 0 5 0 1 1 3 4 4 2 2 1 9 6 5 8 6 3 9 4 4 3 2
 8 4 9]
Most frequent value in the above array:
4


In [13]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])


Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


In [14]:
import numpy as np
arra1 = np.array([("Yasemin Rayner", 88.5, 90),
                 ("Ayaana Mcnamara", 87, 99),
             ("Jody Preece", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)


Original arrays:
[['Yasemin Rayner' '88.5' '90']
 ['Ayaana Mcnamara' '87' '99']
 ['Jody Preece' '85.5' '91']]

Record array;
[(b'Yasemin Rayner', 88.5, 90) (b'Ayaana Mcnamara', 87. , 99)
 (b'Jody Preece', 85.5, 91)]
